// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
export const parser = Parser.deserialize({
  version: 13,
  states: "bOVQPOOOOQO'#Ce'#CeQOQPOO",
  stateData: "e~OWOS~OQPORPOSPOTPO~O",
  goto: "^YPPPPPPPPPZRQO",
  nodeNames: "⚠ Program Int Function Index RightSide",
  maxTerm: 9,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "%O~RXXYnYZn]^npqn!Q![!P!]!^!X#T#U$n#]#^$s#b#c$y~sSW~XYnYZn]^npqn~!UPQ~!Q![!P~![ZX^!Xpq!X!Q![!}#y#z!X$f$g!X#BY#BZ!X$IS$I_!X$I|$JO!X$JT$JU!X$KV$KW!X&FU&FV!X~#S[T~X^#xpq#x|}!X!Q![!}#y#z#x$f$g#x#BY#BZ#x$IS$I_#x$I|$JO#x$JT$JU#x$KV$KW#x&FU&FV#x~#{ZX^#xpq#x|}!X#y#z#x$f$g#x#BY#BZ#x$IS$I_#x$I|$JO#x$JT$JU#x$KV$KW#x&FU&FV#x~$sOR~~$vP#Y#Z$n~%OOS~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
